// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LegacyTape

#include "ui.h"

// COMPONENT WelcomeLabel

lv_obj_t *ui_WelcomeLabel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_WelcomeLabel;
cui_WelcomeLabel = lv_label_create(comp_parent);
lv_obj_set_width( cui_WelcomeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_WelcomeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_WelcomeLabel, 42 );
lv_obj_set_y( cui_WelcomeLabel, -24 );
lv_obj_set_align( cui_WelcomeLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_WelcomeLabel,"Welcome \nTo \nLegacyTape");
lv_obj_set_style_text_color(cui_WelcomeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_WelcomeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_WelcomeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_WelcomeLabel, &ui_font_Archivobig, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_WELCOMELABEL_NUM);
children[UI_COMP_WELCOMELABEL_WELCOMELABEL] = cui_WelcomeLabel;
lv_obj_add_event_cb(cui_WelcomeLabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_WelcomeLabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_WelcomeLabel_create_hook(cui_WelcomeLabel);
return cui_WelcomeLabel; 
}

