// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LegacyTape

#include "ui.h"

// COMPONENT smallerlabel

lv_obj_t *ui_smallerlabel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_smallerlabel;
cui_smallerlabel = lv_label_create(comp_parent);
lv_obj_set_width( cui_smallerlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_smallerlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_smallerlabel, 31 );
lv_obj_set_y( cui_smallerlabel, 101 );
lv_obj_set_align( cui_smallerlabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_smallerlabel,"To get started scan the barcode in \nthe MyLegacyTape app");
lv_obj_set_style_text_color(cui_smallerlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_smallerlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_smallerlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_smallerlabel, &ui_font_Arhivo_regular_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SMALLERLABEL_NUM);
children[UI_COMP_SMALLERLABEL_SMALLERLABEL] = cui_smallerlabel;
lv_obj_add_event_cb(cui_smallerlabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_smallerlabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_smallerlabel_create_hook(cui_smallerlabel);
return cui_smallerlabel; 
}

