// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LegacyTape

#ifndef _LEGACYTAPE_UI_COMP_HOOK_H
#define _LEGACYTAPE_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_WelcomeLabel_create_hook( lv_obj_t *comp );
void ui_comp_smallerlabel_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
