// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LegacyTape

#ifndef _UI_COMP_SMALLERLABEL_H
#define _UI_COMP_SMALLERLABEL_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT smallerlabel
#define UI_COMP_SMALLERLABEL_SMALLERLABEL 0
#define _UI_COMP_SMALLERLABEL_NUM 1
lv_obj_t *ui_smallerlabel_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
