// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LegacyTape

#ifndef _UI_COMP_WELCOMELABEL_H
#define _UI_COMP_WELCOMELABEL_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT WelcomeLabel
#define UI_COMP_WELCOMELABEL_WELCOMELABEL 0
#define _UI_COMP_WELCOMELABEL_NUM 1
lv_obj_t *ui_WelcomeLabel_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
