// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LegacyTape

#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_WelcomeLabel2 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_smallerlabel2 = NULL;lv_obj_t *ui_Button1 = NULL;lv_obj_t *ui_Label1 = NULL;
// event funtions
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen3_screen_init);
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x3A8B95), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WelcomeLabel2 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_WelcomeLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WelcomeLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WelcomeLabel2, -189 );
lv_obj_set_y( ui_WelcomeLabel2, -37 );
lv_obj_set_align( ui_WelcomeLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_WelcomeLabel2,"Your device \nis set up.");
lv_obj_set_style_text_color(ui_WelcomeLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WelcomeLabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_WelcomeLabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WelcomeLabel2, &ui_font_archivo_50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Image2, &ui_img_1240451101);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 654
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 402
lv_obj_set_x( ui_Image2, 184 );
lv_obj_set_y( ui_Image2, 12 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,150);

ui_smallerlabel2 = ui_smallerlabel_create(ui_Screen2);
lv_obj_set_x( ui_smallerlabel2, 32 );
lv_obj_set_y( ui_smallerlabel2, 45 );
lv_label_set_text(ui_smallerlabel2,"Give your first book a name.");

ui_Button1 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button1, 224);
lv_obj_set_height( ui_Button1, 59);
lv_obj_set_x( ui_Button1, -228 );
lv_obj_set_y( ui_Button1, 117 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xE53935), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x8A3024), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label1 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"NAME YOUR BOOK");

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_WelcomeLabel2= NULL;
ui_Image2= NULL;
ui_smallerlabel2= NULL;
ui_Button1= NULL;
ui_Label1= NULL;

}
