// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LegacyTape

#include "ui.h"

lv_obj_t *ui_Screen3 = NULL;lv_obj_t *ui_WelcomeLabel3 = NULL;lv_obj_t *ui_Keyboard2 = NULL;lv_obj_t *ui_TextArea1 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x3A8B95), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WelcomeLabel3 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_WelcomeLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WelcomeLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WelcomeLabel3, 0 );
lv_obj_set_y( ui_WelcomeLabel3, 30 );
lv_obj_set_align( ui_WelcomeLabel3, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_WelcomeLabel3,"Name Your Book");
lv_obj_set_style_text_color(ui_WelcomeLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WelcomeLabel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_WelcomeLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WelcomeLabel3, &ui_font_Archivobig, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard2 = lv_keyboard_create(ui_Screen3);
lv_obj_set_width( ui_Keyboard2, 700);
lv_obj_set_height( ui_Keyboard2, 300);
lv_obj_set_x( ui_Keyboard2, 0 );
lv_obj_set_y( ui_Keyboard2, 75 );
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_CENTER );

ui_TextArea1 = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_TextArea1, 567);
lv_obj_set_height( ui_TextArea1, 50);
lv_obj_set_x( ui_TextArea1, 7 );
lv_obj_set_y( ui_TextArea1, -119 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea1,"Your book name...");

}

void ui_Screen3_screen_destroy(void)
{
   if (ui_Screen3) lv_obj_del(ui_Screen3);

// NULL screen variables
ui_Screen3= NULL;
ui_WelcomeLabel3= NULL;
ui_Keyboard2= NULL;
ui_TextArea1= NULL;

}
