// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LegacyTape

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_WelcomeLabel = NULL;lv_obj_t *ui_smallerlabel = NULL;lv_obj_t *ui_smallerlabel1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x3A8B95), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_qr_card_empty_2_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 592
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 630
lv_obj_set_x( ui_Image1, 91 );
lv_obj_set_y( ui_Image1, -3 );
lv_obj_set_align( ui_Image1, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,150);

ui_WelcomeLabel = ui_WelcomeLabel_create(ui_Screen1);
lv_obj_set_x( ui_WelcomeLabel, 42 );
lv_obj_set_y( ui_WelcomeLabel, -24 );

ui_smallerlabel = ui_smallerlabel_create(ui_Screen1);
lv_obj_set_x( ui_smallerlabel, 31 );
lv_obj_set_y( ui_smallerlabel, 101 );

ui_smallerlabel1 = ui_smallerlabel_create(ui_Screen1);
lv_obj_set_x( ui_smallerlabel1, 31 );
lv_obj_set_y( ui_smallerlabel1, 101 );

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Image1= NULL;
ui_WelcomeLabel= NULL;
ui_smallerlabel= NULL;
ui_smallerlabel1= NULL;

}
